### ISSUE TITLE
If an item is non-magical and thus cannot require attunement, spells from Cast activities do not appear on the character sheet

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#5120]
They can still be used, though.

While there are few (probably none?) items that are nonmagical but allow a spell to be cast, this seems like an oversight.

(dnd5e 4.2.2)

**Comment by Fyorl** [comment]
Probably handled by activity visibility logic but will mark it as a bug for now.

**Comment by arbron** [comment]
This is caused because we check `magicAvailable`, which only exists in `EquippableItemTemplate`. I've fixed that in my Antimagic region PR (see https://github.com/foundryvtt/dnd5e/pull/6030), but I can pull the fix for it back pretty easily since it just involves moving that method from `EquippableItemTemplate` to `ItemDataModel`.

**Comment by CS-Birb** [comment]
Issue still present in 5.1.8, following the revert of 5df11b0

Relates to #6108 

Mechanics-wise, an example I've seen for non-magical items with Cast activities would be Spellbooks, or a Warlock's Book of Shadows (SRD5.2 and PHB content). Is there a reason to hide those in particular, rather than just in the case of Attunement Required?
